import {itCases} from '@augment-vir/chai';
import {testRepos} from '../../test-helpers/file-paths.test-helper';
import {getNpmPackages} from './get-npm-packages';

describe(getNpmPackages.name, () => {
    itCases(getNpmPackages, [
        {
            it: 'gets only typescript project directories',
            input: testRepos['augment-vir'],
            expect: [
                {
                    dirRelativePath: 'packages/browser',
                    npmName: '@augment-vir/browser',
                    allDeps: [
                        '@augment-vir/browser-testing',
                        '@open-wc/testing',
                        '@types/mocha',
                        '@web/dev-server-esbuild',
                        '@web/test-runner',
                        '@web/test-runner-commands',
                        '@web/test-runner-playwright',
                        '@web/test-runner-visual-regression',
                        'element-vir',
                        'istanbul-smart-text-reporter',
                        'typescript',
                        '@augment-vir/common',
                    ],
                },
                {
                    dirRelativePath: 'packages/browser-testing',
                    npmName: '@augment-vir/browser-testing',
                    allDeps: [
                        '@web/dev-server-esbuild',
                        '@web/test-runner',
                        '@web/test-runner-playwright',
                        '@web/test-runner-visual-regression',
                        'istanbul-smart-text-reporter',
                        'typescript',
                        '@augment-vir/common',
                        '@augment-vir/testing',
                        '@open-wc/testing',
                        '@types/mocha',
                        '@web/test-runner-commands',
                        'type-fest',
                    ],
                },
                {
                    dirRelativePath: 'packages/chai',
                    npmName: '@augment-vir/chai',
                    allDeps: [
                        'typescript',
                        '@augment-vir/common',
                        '@augment-vir/testing',
                        '@types/chai-as-promised',
                        'chai-as-promised',
                        'expect-type',
                        'test-established-expectations',
                        'type-fest',
                    ],
                },
                {
                    dirRelativePath: 'packages/common',
                    npmName: '@augment-vir/common',
                    allDeps: [
                        'typescript',
                        'type-fest',
                    ],
                },
                {
                    dirRelativePath: 'packages/common-tests',
                    npmName: '@augment-vir/common-tests',
                    allDeps: [
                        '@augment-vir/chai',
                        '@augment-vir/node-js',
                        '@electrovir/nyc',
                        '@istanbuljs/nyc-config-typescript',
                        '@types/chai',
                        '@types/mocha',
                        'chai',
                        'expect-type',
                        'istanbul-smart-text-reporter',
                        'mocha',
                        'mocha-spec-reporter-with-file-names',
                        'ts-node',
                        'type-fest',
                        'typescript',
                    ],
                },
                {
                    dirRelativePath: 'packages/docker',
                    npmName: '@augment-vir/docker',
                    allDeps: [
                        'typescript',
                        '@augment-vir/common',
                        '@augment-vir/node-js',
                    ],
                },
                {
                    dirRelativePath: 'packages/element-vir',
                    npmName: '@augment-vir/element-vir',
                    allDeps: [
                        '@augment-vir/browser-testing',
                        '@open-wc/testing',
                        '@types/mocha',
                        '@web/dev-server-esbuild',
                        '@web/test-runner',
                        '@web/test-runner-commands',
                        '@web/test-runner-playwright',
                        '@web/test-runner-visual-regression',
                        'istanbul-smart-text-reporter',
                        'typescript',
                        '@augment-vir/common',
                    ],
                },
                {
                    dirRelativePath: 'packages/node-js',
                    npmName: '@augment-vir/node-js',
                    allDeps: [
                        '@augment-vir/chai',
                        '@electrovir/nyc',
                        '@istanbuljs/nyc-config-typescript',
                        '@types/chai',
                        '@types/chai-as-promised',
                        '@types/fs-extra',
                        '@types/mocha',
                        '@types/node',
                        'chai',
                        'chai-as-promised',
                        'istanbul-smart-text-reporter',
                        'mocha',
                        'mocha-spec-reporter-with-file-names',
                        'ts-node',
                        'typescript',
                        '@augment-vir/common',
                        'ansi-colors',
                        'axios',
                        'fs-extra',
                        'ts-node',
                        'type-fest',
                    ],
                },
                {
                    dirRelativePath: 'packages/prisma-node-js',
                    npmName: '@augment-vir/prisma-node-js',
                    allDeps: [
                        'istanbul-smart-text-reporter',
                        'typescript',
                        '@augment-vir/common',
                        '@augment-vir/node-js',
                    ],
                },
                {
                    dirRelativePath: 'packages/scripts',
                    npmName: '@augment-vir/scripts',
                    allDeps: [
                        '@electrovir/nyc',
                        '@istanbuljs/nyc-config-typescript',
                        '@types/chai',
                        '@types/mocha',
                        '@types/node',
                        'chai',
                        'istanbul-smart-text-reporter',
                        'mocha',
                        'mocha-spec-reporter-with-file-names',
                        'ts-node',
                        'type-fest',
                        'typescript',
                        '@augment-vir/common',
                        '@augment-vir/node-js',
                    ],
                },
                {
                    dirRelativePath: 'packages/testing',
                    npmName: '@augment-vir/testing',
                    allDeps: [
                        '@electrovir/nyc',
                        '@istanbuljs/nyc-config-typescript',
                        '@types/mocha',
                        'chai',
                        'istanbul-smart-text-reporter',
                        'mocha',
                        'mocha-spec-reporter-with-file-names',
                        'ts-node',
                        'typescript',
                        '@augment-vir/common',
                        '@types/chai',
                        'expect-type',
                        'mock-vir',
                        'type-fest',
                    ],
                },
            ],
        },
    ]);
});
